// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqYwbBXlLI_U_AIDnegTDqLuWtmu8Et3Y',
    appId: '1:95271790157:android:0bbac2c6056908f01b9e04',
    messagingSenderId: '95271790157',
    projectId: 'bone-abnormality-detector',
    storageBucket: 'bone-abnormality-detector.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWT-BQHd5qg37fGzgty7tjGCWiLFDn2X0',
    appId: '1:95271790157:ios:7379836f8edb3d9a1b9e04',
    messagingSenderId: '95271790157',
    projectId: 'bone-abnormality-detector',
    storageBucket: 'bone-abnormality-detector.firebasestorage.app',
    iosBundleId: 'com.example.boneAbnormalityDetector',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj10TUUkO_8Qov2T_PpWBL6cwvFFIwqhM',
    appId: '1:95271790157:web:dcc66c28e41a97c21b9e04',
    messagingSenderId: '95271790157',
    projectId: 'bone-abnormality-detector',
    authDomain: 'bone-abnormality-detector.firebaseapp.com',
    storageBucket: 'bone-abnormality-detector.firebasestorage.app',
    measurementId: 'G-2CVBWK20KW',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWT-BQHd5qg37fGzgty7tjGCWiLFDn2X0',
    appId: '1:95271790157:ios:7379836f8edb3d9a1b9e04',
    messagingSenderId: '95271790157',
    projectId: 'bone-abnormality-detector',
    storageBucket: 'bone-abnormality-detector.firebasestorage.app',
    iosBundleId: 'com.example.boneAbnormalityDetector',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj10TUUkO_8Qov2T_PpWBL6cwvFFIwqhM',
    appId: '1:95271790157:web:67db924efb5969cb1b9e04',
    messagingSenderId: '95271790157',
    projectId: 'bone-abnormality-detector',
    authDomain: 'bone-abnormality-detector.firebaseapp.com',
    storageBucket: 'bone-abnormality-detector.firebasestorage.app',
    measurementId: 'G-SJGPJYGH5J',
  );

}